### PR TITLE
Update README.md with Intel Quick Sync and clearer instructions

### PR DESCRIPTION
**Pull request by martiperez**
Added description for using Intel Quick Sync. Also added clarifications regarding when to run commands with the immich user or with the sudo/root user.

### CODE REVIEW

**Comment by loeeeee** [comment]
Sorry about the delay. I was taking a rest after the exam period.

Thanks for your contribution. 😃 

I took a look at the changes, and had one slight issue.

- Including the QuickSync guide in this repo may not be the best idea.
    - I do not have a Intel machine with QuickSync capability to test on, and if I include those in this repo, then, I would have to be able to solve the issues regarding Quick Sync or you will need to stick around, solving issues.
    - To solve the liability issue, it would be better if Quick Sync support is kept as a fork of this repository, and we could include links to each other's repository so that we could both do what we can do to solve the issues of the users.

I am very open to discussion, and please feel free to propose a better solution or argue otherwise. 😃

**Comment by loeeeee** [comment]
Also, your pull request quality is great!

**Comment by havardthom** [comment]
Hello, I ended up here after going down the Immich on Proxmox rabbit hole. I will be trying out this Immich setup in lxc (with Quick Sync) this weekend. Just wanted to add my two cents to your concerns as a random bypasser. 

I feel like adding a optional Quick Sync section to this guide would be a great addition and it fits naturally next to the CUDA setup. Many home server users run Proxmox on a mini PC with Intel CPU and it would be a great resource for them. Creating yet a separate guide for this section does seem inconvenient and will make the Immich on Proxmox rabbit hole deeper. Though I perfectly understand your concerns on not being able to solve issues in this section. 

Perhaps a solution could be adding a disclaimer to the Quick Sync section, stating `The guide maintainer can not provide support for this section, any issues regarding Quick Sync must be resolved by the community` or something similar you can refer to if any issues occur.

I will atleasy try this guide soon and give my feedback :) Thank you for the great work!

**Comment by martiperez** [comment]
> I am very open to discussion, and please feel free to propose a better solution or argue otherwise. 😃

Of course I understand! I already edited the guide accordingly (second commit). I still left a message on the section "Hardware-accelerated machine learning: Others (Optional)", but it's a very minor one pointing to an external tutorial.


> I will atleasy try this guide soon and give my feedback :) Thank you for the great work!

If @havardthom tries it and it works well, you can consider bringing it back by doing another pull request (just align with @loeeeee before).
@havardthom  - you can still access the uncommited guide [here](https://github.com/loeeeee/immich-in-lxc/blob/8d5c97562dd84cdb9a131497ec29924dff3c86f1/README.md)

**Pull request merged**
